COMMAND_PREFIX = "~b "
CONFIG_FILENAME = "botaclan"
FEATURE_CALENDAR = True
FEATURE_MUSICPLAYER = True
FEATURE_ROULETTE = True
GOOGLEAPI_APPLICATION_CREDENTIALS = "/etc/botaclan/google_service_account.json"
GOOGLEAPI_CALENDAR_ID = "primary"
HEALTHCHECK_HOST = "0.0.0.0"
HEALTHCHECK_PORT = 8080
LOG_ASYNCIO_LEVEL = "warning"
LOG_DISCORD_LEVEL = "warning"
LOG_LEVEL = "info"
LOG_UVICORN_LEVEL = "info"
LOG_WEBSOCKETS_LEVEL = "warning"
SENTRY_ENABLED = False
SUPPORTED_CONFIG_EXTENSIONS = ["yaml"]
SUPPORTED_CONFIG_PATHS = ["/etc/botaclan/", "$HOME/.botaclan/", "."]
SUPPORTED_GOOGLEAPI_CALENDAR_ROLES = ["owner", "writer", "reader"]
SUPPORTED_LOG_LEVELS = ["critical", "error", "warning", "info", "debug"]
SUPPORTED_MUSICPLAYER_PROVIDERS = ["youtube", "soundcloud"]
TIMEZONE = "America/Sao_Paulo"
